/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kalkulator;

import javafx.application.Application;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.image.ImageView;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.scene.text.Text;
import javafx.stage.Stage;

public class App extends Application {
    private Stage stage;

    @Override
    public void start(Stage mainStage) {

        stage = mainStage;
        stage.setTitle("Tugas Praktikum 9");
        stage.setScene(getScene1());
        stage.setResizable(false);
        stage.show();
    }

    private Scene getScene1() {

        Text tTitle = new Text("KALKULATOR KONVERSI CELCIUS");
        tTitle.setStyle("-fx-text-fill: red;");
        // tTitle.getStyleClass().add("text");
        // System.out.println(tTitle.getStyleClass());
        Button bMulai = new Button("Mulai");
        VBox sectionRight = new VBox(tTitle, bMulai);

        sectionRight.setAlignment(Pos.CENTER);
        sectionRight.setPrefWidth(30);

        bMulai.setOnAction(v -> {
            stage.setScene(getScene2());
        });

        ImageView ivBanner = new ImageView("/images/calculator.png");
        ivBanner.setFitWidth(300);
        ivBanner.setFitHeight(500);
        ivBanner.setPreserveRatio(true);

        VBox rootNode = new VBox(ivBanner, sectionRight);
        rootNode.setAlignment(Pos.CENTER);

        Scene scene = new Scene(new StackPane(rootNode), 300, 500);

        scene.getStylesheets().add(getClass().getResource("/styles/style.css").toExternalForm());
        return scene;
    }

    private Scene getScene2() {
        Text tTitle = new Text("KONVERSI KE-");
        Button bKalkulator1 = new Button("Fahrenheit");
        Button bKalkulator2 = new Button("Reamur");
        Button bKalkulator3 = new Button("Kelvin");
        VBox sectionRight = new VBox(tTitle, bKalkulator1, bKalkulator2, bKalkulator3);
        sectionRight.setSpacing(50);
        sectionRight.setAlignment(Pos.CENTER);
        sectionRight.setPrefWidth(0);

        bKalkulator1.setOnAction(v -> {
            stage.setScene(getScene3("Fahrenheit", true));
        });

        bKalkulator2.setOnAction(v -> {
            stage.setScene(getScene3("Reamur", true));
        });

        bKalkulator3.setOnAction(v -> {
            stage.setScene(getScene3("Kelvin", true));
        });

        VBox rootNode = new VBox(sectionRight);

        Scene scene = new Scene(new StackPane(rootNode), 300, 500);

        scene.getStylesheets().add(getClass().getResource("/styles/style.css").toExternalForm());
        return scene;

    }

    private Scene getScene3(String kalkulator, boolean celcius) {
        Text tTitle = new Text("Jenis Kalkulator : " + kalkulator);
        Label lInput1 = new Label("Input celcius");
        TextField tInput1 = new TextField("0");

        Label lHasil = new Label();
        // lHasil.setStyle("-fx-text-fill: red;");
        
        Button bClear = new Button("Clear");
        Button bCalculate = new Button("Calculate");
        Button bBackToHome = new Button("BACK TO HOME");

        VBox sectionRight;

        sectionRight = new VBox(tTitle, lInput1, tInput1, lHasil, bClear, bCalculate, bBackToHome);
        sectionRight.setSpacing(15);
        sectionRight.setAlignment(Pos.CENTER);
        sectionRight.setPrefWidth(0);

        bClear.setOnAction(v -> {
            tInput1.clear();
        });

        bCalculate.setOnAction(v -> {
            try {
                Double.parseDouble(tInput1.getText());
                double fahrenheit = Double.parseDouble(tInput1.getText()) * 1.8 + 32;
                double reamur = Double.parseDouble(tInput1.getText()) * 0.8;
                double kelvin = Double.parseDouble(tInput1.getText()) + 273;
                double hasil = 0;

                if (kalkulator.equals("Fahrenheit")) {
                    hasil = fahrenheit;
                } else if (kalkulator.equals("Reamur")) {
                    hasil = reamur;
                } else if (kalkulator.equals("Kelvin")) {
                    hasil = kelvin;
                }

                lHasil.setText("Hasil: " + hasil);

            } catch (NumberFormatException e) {
                lHasil.setText("Input suhu");

            }
        });

        bBackToHome.setOnAction(v -> {
            stage.setScene(getScene2());
        });

        VBox rootNode = new VBox(sectionRight);

        Scene scene = new Scene(new StackPane(rootNode), 300, 500);

        scene.getStylesheets().add(getClass().getResource("/styles/style.css").toExternalForm());
        return scene;

    }

    public static void main(String[] args) {
        launch();
    }

}